### ISSUE TITLE
CSS引入的方式

### ISSUE THREAD

**Issue by Monkey626** [Monkey626/front-end#29]
### 内联
直接在标签的style属性中设定CSS样式。
```css
<div style="width:300px; height:200px; background-color:black;"></div>
```

### 内嵌
将CSS样式集中写在网页的<head></head>标签对的<style></style>标签对中。
```css
<style type="text/css">
        div{
            width: 300px;
            height: 200px;
            background-color: red;
        }
    </style>
```

### 链接
使用<link>标签来引入外部css样式表文件。
```css
<link rel="stylesheet" type="text/css" href="test.css">
```

### 导入
在<style></style>标签对使用CSS规则引入外部CSS文件。
```css
<style type="text/css">
        @import url("test.css");
</style>
```
